services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    init: true
    ipc: host
    network_mode: host
    env_file:
      - ./backend/.env
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./backend/data:/app/data
      - ./backend/logs:/app/logs
      - ./backend/config.yaml:/app/config.yaml
      - /tmp/.X11-unix:/tmp/.X11-unix

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.local
